Repository theforeman/puppet-certs, pull requests merged in 2018-10, with the labels that each got.

#211 set empty-password for nssdb as FIPS fails on password file
  manifests/ssltools/certutil.pp
Labels: Needs re-review, Needs testing

#218 Release 4.3.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#220 Add support for debian derivatives
  templates/rhsm-katello-reconfigure.erb
Labels: Needs testing, Not yet reviewed

#219 Update README
  README.md
Labels: Needs testing, Not yet reviewed

#222 Rewrite validate_file_exists to a modern Ruby function
  lib/puppet/functions/validate_file_exists.rb
  lib/puppet/parser/functions/validate_file_exists.rb
  spec/functions/validate_file_exists_spec.rb
Labels: Enhancement, Needs testing

#223 Fixes #25359 - Add name flag to openssl pkcs12 nsddb key/cert convert.
  manifests/qpid.pp
  spec/classes/certs_qpid_spec.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
