Repository theforeman/puppet-certs, pull requests merged in 2019-02, with the labels that each got.

#241 Release 5.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#229 Move qpid client cert to /etc/pki/pulp
  manifests/params.pp
  manifests/qpid_client.pp
  spec/classes/certs_qpid_client_spec.rb
Labels: Backwards incompatible, Needs re-review, Needs testing

#244 Add nssdb files for EL8
  manifests/ssltools/nssdb.pp
Labels: Needs testing, Not yet reviewed

#243 Fixes #26088 - ensure RSA word for SSLProxyMachineCertificateFile
  lib/puppet/provider/katello_ssl_tool.rb
  lib/puppet/type/certs_common.rb
  manifests/foreman_proxy.pp
Labels: Bug, Needs testing

#246 Fixes #26119 - don't use md5 for digesting
  lib/puppet/provider/katello_ssl_tool.rb
Labels: Enhancement, Needs testing

#245 Add CA cert to keystore as a trustedcert
  manifests/candlepin.pp
  spec/acceptance/candlepin_spec.rb
Labels: Needs testing, Not yet reviewed
