Repository theforeman/puppet-certs, pull requests merged in 2020-08, with the labels that each got.

#296 Release 9.0.0
  CHANGELOG.md
  HISTORY.md
Labels: Needs testing, skip-changelog

#301 Remove unused $katello_* params
  manifests/params.pp
Labels: Needs testing

#294 Refs #30316: Cleanup bootstrap RPM generation code
  files/postun.sh
  lib/puppet/provider/certs_bootstrap_rpm/katello_ssl_tool.rb
  lib/puppet/type/certs_bootstrap_rpm.rb
Labels: Backwards incompatible, Needs testing
