Repository theforeman/puppet-certs, pull requests merged in 2020-07, with the labels that each got.

#291 Refs #30346: Generate a separate truststore for Candlepin
  manifests/candlepin.pp
  manifests/params.pp
  spec/acceptance/candlepin_spec.rb
Labels: Needs testing

#292 Bump version to 9.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#290 Refs #30316: Drop bootstrap RPM code
  manifests/katello.pp
  spec/classes/certs_katello_spec.rb
  templates/rhsm-katello-reconfigure.erb
Labels: Backwards incompatible, Needs testing

#295 Refs #30346 - allow override of candlepin client keypair group
  manifests/candlepin.pp
Labels: Needs testing
