Repository theforeman/puppet-certs, pull requests merged in 2021-06, with the labels that each got.

#346 Declare the build directory for all certificate creation
  lib/puppet/provider/ca/katello_ssl_tool.rb
  lib/puppet/provider/cert/katello_ssl_tool.rb
  lib/puppet_x/certs/common.rb
  manifests/apache.pp
  manifests/ca.pp
  manifests/candlepin.pp
  manifests/foreman.pp
  manifests/foreman_proxy.pp
  manifests/pulp_client.pp
  manifests/puppet.pp
  manifests/qpid.pp
  manifests/qpid_router/client.pp
  manifests/qpid_router/server.pp
Labels: Needs testing

#350 Remove dependency on trusted_ca
  .fixtures.yml
  metadata.json
Labels: Enhancement, Needs testing, Not yet reviewed

#351 Add acceptance tests for tar_create and tar_extract
  spec/acceptance/apache_spec.rb
  spec/acceptance/candlepin_spec.rb
  spec/acceptance/certs_spec.rb
  spec/acceptance/certs_tar_extract_spec.rb
  spec/acceptance/foreman_proxy_content_spec.rb
  spec/acceptance/foreman_proxy_spec.rb
  spec/acceptance/qpid_spec.rb
Labels: Needs testing

#357 Add acceptance tests for certs::pulp_client
  spec/acceptance/pulp_client_spec.rb
Labels: Needs testing

#347 Add match_without_whitespace custom matcher
  spec/acceptance/qpid_spec.rb
  spec/support/acceptance/matchers/match_without_whitespace.rb
Labels: Waiting on contributor, skip-changelog

#358 Add acceptance tests for certs::puppet
  spec/acceptance/puppet_spec.rb
Labels: Needs testing

#352 Include certs directory tarball
  manifests/tar_create.pp
  spec/acceptance/certs_tar_extract_spec.rb
Labels: Needs testing

#363 Test that foreman client_cert.pem has keylength >= 4096
  spec/acceptance/foreman_spec.rb
Labels: Needs testing, skip-changelog

#343 Bump master to 13.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#364 Add acceptance test for truststore_certificate
  spec/acceptance/truststore_spec.rb
Labels: Needs testing

#345 Drop Puppet 5 support
  metadata.json
Labels: Backwards incompatible, Needs testing

#361 Remove SSL certificate DN normalization workaround
  spec/acceptance/apache_spec.rb
  spec/acceptance/candlepin_spec.rb
  spec/acceptance/certs_spec.rb
  spec/acceptance/certs_tar_extract_spec.rb
  spec/acceptance/foreman_proxy_spec.rb
  spec/acceptance/foreman_spec.rb
  spec/acceptance/pulp_client_spec.rb
  spec/acceptance/puppet_spec.rb
  spec/acceptance/qpid_router_client_spec.rb
  spec/acceptance/qpid_router_server_spec.rb
  spec/acceptance/qpid_spec.rb
  spec/support/acceptance/openssl.rb
Labels: Needs testing

#335 Fixes #32631: Add keystore_certificate provider type
  lib/puppet/provider/keystore_certificate/openssl.rb
  lib/puppet/type/keystore_certificate.rb
  manifests/candlepin.pp
  spec/acceptance/candlepin_spec.rb
Labels: Enhancement, Needs testing

#332 Fixes #32585: Add function to extract Artemis client certificate subj…
  lib/puppet/functions/certs/certificate_subject.rb
  manifests/candlepin.pp
  spec/functions/certs_certificate_subject_spec.rb
Labels: Enhancement, Needs testing
