Repository theforeman/puppet-certs, pull requests merged in 2021-05, with the labels that each got.

#325 Allow Puppet 7 compatible versions of mods
  metadata.json
Labels: Needs testing, Not yet reviewed

#326 Add acceptance tests for certs::qpid
  spec/acceptance/qpid_spec.rb
Labels: Needs testing

#333 Bump master to 12.1.0
  metadata.json
Labels: Needs testing

#327 Fixes #32506: Add an nssdb_certificate type and provider
  lib/puppet/provider/nssdb_certificate/certutil.rb
  lib/puppet/type/nssdb_certificate.rb
  manifests/qpid.pp
  spec/acceptance/qpid_spec.rb
  spec/classes/certs_qpid_spec.rb
Labels: Enhancement, Needs testing

#337 Fixes #32647: Do not show diff on password files
  manifests/ca.pp
  manifests/candlepin.pp
Labels: Needs testing

#338 Switch to voxpupuli-acceptance-1.0
  Gemfile
  spec/acceptance/apache_spec.rb
  spec/acceptance/candlepin_spec.rb
  spec/acceptance/certs_spec.rb
  spec/acceptance/foreman_proxy_spec.rb
  spec/acceptance/qpid_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Needs testing

#334 Fixes #32506: Add keystore puppet provider type
  lib/puppet/provider/keystore/keytool.rb
  lib/puppet/type/keystore.rb
  manifests/candlepin.pp
Labels: Enhancement, Needs testing

#340 Add acceptance tests for keystore provider
  lib/puppet/provider/keystore/keytool.rb
  spec/acceptance/candlepin_spec.rb
  spec/acceptance/keystore.rb
Labels: Needs testing, Not yet reviewed

#341 Refs #32506 - Avoid in place modification of array
  lib/puppet/type/keystore.rb
Labels: Bug, Needs testing

#336 Fixes #32637: Add truststore type and provider
  lib/puppet/provider/keystore/keytool.rb
  lib/puppet/provider/truststore/keytool.rb
  lib/puppet/type/truststore.rb
  lib/puppet_x/certs/provider/keystore.rb
  manifests/candlepin.pp
  spec/acceptance/truststore_spec.rb
Labels: Enhancement, Needs testing
