Repository theforeman/puppet-certs, pull requests merged in 2021-08, with the labels that each got.

#378 Fix beaker task
  .github/workflows/ci.yml
  Gemfile
  Rakefile
Labels: Modulesync, Needs testing, Not yet reviewed

#377 Add types for parameters for all classes
  manifests/apache.pp
  manifests/ca.pp
  manifests/candlepin.pp
  manifests/config.pp
  manifests/foreman.pp
  manifests/foreman_proxy.pp
  manifests/pulp_client.pp
  manifests/puppet.pp
  manifests/qpid.pp
  manifests/qpid_router/client.pp
  manifests/qpid_router/server.pp
  manifests/ssltools/certutil.pp
  manifests/tar_create.pp
  manifests/tar_extract.pp
Labels: Needs testing

#379 Allow passing string for hostname to certs::qpid_router::client
  manifests/qpid_router/client.pp
Labels: Needs testing, Not yet reviewed
