Repository theforeman/puppet-certs, pull requests merged in 2021-07, with the labels that each got.

#369 Revert "Fixes #32585: Add function to extract Artemis client certific…
  lib/puppet/functions/certs/certificate_subject.rb
  manifests/candlepin.pp
  spec/functions/certs_certificate_subject_spec.rb
Labels: Needs testing, Not yet reviewed

#365 Support ensuring certs::keypair cert and key can be absent
  lib/puppet/provider/katello_ssl_tool.rb
  lib/puppet/provider/key_bundle/katello_ssl_tool.rb
  lib/puppet_x/certs/common.rb
  manifests/keypair.pp
  spec/defines/keypair_spec.rb
Labels: Needs testing

#371 Fixes #32382: Use certs::foreman client certificate to communicate wi…
  manifests/candlepin.pp
  manifests/foreman.pp
  spec/acceptance/candlepin_spec.rb
  spec/acceptance/foreman_spec.rb
Labels: Needs testing

#344 Fixes #32511 - Add a puppet type and provider to manage an nssdb
  lib/puppet/provider/nssdb/certutil.rb
  lib/puppet/type/nssdb.rb
  manifests/init.pp
  manifests/ssltools/nssdb.pp
  spec/acceptance/qpid_spec.rb
  spec/classes/certs_qpid_spec.rb
Labels: Enhancement, Needs testing

#374 Add owner, group parameters to certs::foreman
  manifests/foreman.pp
Labels: Enhancement, Needs testing

#375 Manage the certs::foreman ssl_ca_file
  manifests/foreman.pp
  spec/acceptance/foreman_spec.rb
Labels: Needs testing

#373 Release 13.0.0
  CHANGELOG.md
Labels: Needs testing, skip-changelog
