Repository theforeman/puppet-certs, pull requests merged in 2022-03, with the labels that each got.

#392 Allow stdlib 8.x, extlib 6.x
  metadata.json
Labels: Needs testing

#393 Switch to gha-puppet for CI
  .github/workflows/ci.yml
  Gemfile
Labels: Needs testing, Modulesync

#394 Fixes #34598: Disable fips for keytool
  lib/puppet/provider/keystore_certificate/openssl.rb
  lib/puppet/provider/truststore_certificate/keytool.rb
  lib/puppet_x/certs/provider/keystore.rb
Labels: Needs testing

#395 Release 15.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
