Repository theforeman/puppet-certs, pull requests merged in 2023-11, with the labels that each got.

#427 Update gems to support testing Puppet 8
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  Gemfile
Labels: Not yet reviewed, Modulesync

#412 Add Puppet 8 support
  metadata.json
Labels: Enhancement

#437 Mark compatible with puppet-extlib 7.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#439 Release 17.0.0
  CHANGELOG.md
Labels: skip-changelog
