Repository theforeman/puppet-certs, pull requests merged in 2024-05, with the labels that each got.

#426 Remove deploy via provider
  lib/puppet/provider/ca/katello_ssl_tool.rb
  lib/puppet/provider/cert/katello_ssl_tool.rb
  lib/puppet/provider/katello_ssl_tool.rb
  lib/puppet_x/certs/common.rb
  manifests/apache.pp
  manifests/ca.pp
  manifests/candlepin.pp
  manifests/foreman.pp
  manifests/foreman_proxy.pp
  manifests/init.pp
  manifests/puppet.pp
Labels: Backwards incompatible

#452 Release 18.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#451 Drop absent file declarations
  manifests/ca.pp
  manifests/candlepin.pp
Labels: Not yet reviewed, Backwards incompatible
